# Use Elixir master instead of a release in order to test Elixir 1.8 functionality
language: erlang
otp_release:
  - 21.0
before_install:
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir && git checkout master && make && cd ..
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.rebar --force
  - mix local.hex --force
  - MIX_ENV=test mix do deps.get
script:
  - mix test
